name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/WslTamer.UI/WslTamer.UI.csproj

    - name: Build
      run: dotnet build src/WslTamer.UI/WslTamer.UI.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish src/WslTamer.UI/WslTamer.UI.csproj --configuration Release --runtime win-x64 --self-contained false --output ./publish

    - name: Extract Version
      run: |
        $version = "${{ github.ref_name }}".TrimStart('v')
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Build Installer
      run: dotnet build src/WslTamer.Installer/WslTamer.Installer.wixproj -c Release /p:DefineConstants="Version=$env:VERSION;PublishDir=..\..\publish"

    - name: Zip Release
      run: Compress-Archive -Path ./publish/* -DestinationPath WslTamer-win-x64.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: |
          WslTamer-win-x64.zip
          src/WslTamer.Installer/bin/Release/WslTamer.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
